input_boolean:
  mode_home:
    name: Anwesend
    initial: off
    icon: mdi:home

  mode_away:
    name: Abwesend
    initial: off
    icon: mdi:tram

  mode_sleep:
    name: Gutenacht
    initial: off
    icon: mdi:sleep

  mode_vecation:
    name: Urlaubsmodus
    initial: off
    icon: mdi:airplane-takeoff

  disable_home_away:
    name: Wechsel Anwesend-Abwesend ausschalten
    initial: off
    icon: mdi:switch

#######################################
# Setting the Profiles for different
# actions.
#
#######################################
#######################################
#######################################
automation:

   #############################################
   # Turn into Vecation mode after time away
   #############################################
  - alias: Automatic Vacation mode after 24 hours

    trigger:
      platform: state
      entity_id: group.family
      from: 'home'
      to: 'not_home'
      for:
        hours: 24
        minutes: 0
        seconds: 0

    condition:
      condition: state
      entity_id: intput_boolean.disable_home_away
      state: 'off'

    action:
      service: homeassistant.turn_on
      entity_id: input_boolean.mode_vecation

  - alias: Schlafmodus deaktivieren

    trigger:
      platform: sun
      event: sunrise
      offset: '-00:45:00'

    condition:
      condition: state
      entity_id: input_boolean.mode_sleep
      state: 'on'

    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.mode_sleep
